{
  "services": [
    {
      "name": "sems-backend",
      "type": "web",
      "env": "node",
      "region": "oregon",
      "plan": "free",
      "branch": "main",
      "buildCommand": "npm install",
      "startCommand": "npm run backend",
      "envVars": [
        {
          "key": "NODE_VERSION",
          "value": "18"
        },
        {
          "key": "MONGODB_URI",
          "value": "mongodb+srv://takyiamy2019_db:sjtaoOULf3Nyr9sb@sems-cluster.atwkdw2.mongodb.net/?retryWrites=true&w=majority&appName=Sems-Cluster"
        }
      ]
    }
  ]
}